import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import Notification from "@/components/ui/notification";
import {NotificationContextProvider} from "@/store/notification-context";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NotificationContextProvider>
            <Layout>
                {children}
                <Notification title={"Test"} message={"This is a test"} status={"success"}/>
            </Layout>
        </NotificationContextProvider>
        </body>
        </html>
    );
}
